control_node:
  ros__parameters:
    enabled: True          # Controla si el tracking_node está activo o no.
    camera_enabled: True   # Controla si el visual_detection_node se va a usar, en caso de estar activado no se utilizará el control por gestos.

tracking_node:
  ros__parameters:
    enabled: True  # Controla si el tracking_node está activo o no.

visual_detection_node:
  ros__parameters:
    enabled: True   # Controla si el visual_detection_node está activo o no.

detection_node:
  ros__parameters:
    enabled: True   # Controla si el detection_node está activo o no.

user_interface_node:
  ros__parameters:
    enabled: True  # Controla si el user_interface_node está activo o no.

